// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umiqvigdibyvieslahcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtaXF2aWdkaWJ5dmllc2xhaGNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNzg4NTgsImV4cCI6MjA3MjY1NDg1OH0.vVMDK6NOzXeRIlZ8TPGVOH0H4OxH3xLuSUGaHWHw9NM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});